name: otachaki
description: Otachaki - Go position evaluation training app

version: 1.1.1+3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0+1
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.26.2

flutter:
  uses-material-design: true
  assets:
    - assets/mid_fox_19x19.json
    - assets/final_19x19_katago.json
    - assets/final_13x13_katago.json
    - assets/final_9x9_katago.json